service: aws-serverless-step-functions

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1

plugins:
  - serverless-step-functions

functions:
  hello:
    handler: handler.hello


